join-message: ""
leave-message: ""

default-gamemode: ADVENTURE


items:
  0:
    material: NETHER_STAR
    amount: 1
    displayname: ""
    lore:
      - ""
      - ""
    action: NONE
    action-properties: ""


data-storing: JSON
# Login information for MySQL
mysql:
  hostname: ""
  user: ""
  password: ""
  port: 3306
  database-name: ""

# Don't touch this!!! This will break the plugin if you change it!
config-version: "v0.1"