name: StarLobby
version: '${project.version}'
main: de.creeperbuildings.starlobby.Main
api-version: 1.13
authors: [CreeperBuildings, PhastixTV, ech0_Schokolade, Julian Weinelt]
description: A complete feature-packed lobby plugin.


permissions:
  starlobby:
    children:
      command:
        children:
          help:
            default: true
            description: Custom Help Command
          gm:
            children:
              - gma
              - gms
              - gmc
              - gmsp
          vanish:
            description: Vanish Command


commands:
  gma:
    aliases:
      - gmc
      - gms
      - gmsp
  help:
    aliases:
      - h