name: StarLobby
version: '${project.version}'
main: de.creeperbuildings.starlobby.Main
api-version: 1.13
authors: [CreeperBuildings, PhastixTV, ech0_Schokolade, Julian Weinelt]
description: Very Nice Lobby Plugin


permissions:
  starlobby:
    children:
      command:
        children:
          help:
            default: true
            description: Custom Help Command
          gm:
            children:
              - gma
              - gms
              - gmc
              - gmsp
          vanish:
            description: Vanish Command