# Do you want to be notified when a newer version available?
check-for-updates: true

join-message: ""
leave-message: ""


# Gamemode on join
default-gamemode: ADVENTURE

# Items given to a player on join.
items:
  0:
    material: NETHER_STAR
    amount: 1
    displayname: ""
    lore:
      - ""
      - ""
    action: NONE
    action-properties: ""

join-position:
  x: 0
  y: 0
  z: 0
  world: "world"
  yaw: 0
  pitch: 0


# How data should be stored. Available: JSON, MYSQL, H2, MONGODB, MARIADB
data-storing: JSON

# Login information for MySQL
mysql:
  hostname: ""
  user: ""
  password: ""
  port: 3306
  database-name: ""


scoreboard:
  # Do you want to use our scoreboard integration?
  enabled: true
  # The scoreboard will not be displayed in this worlds
  blacklisted-worlds: []
  # The blacklist will be handled like a white list
  invert-blacklist: false
  # How often the Scoreboard should be refreshed (in Ticks)
  refresh-rate: 1
  # Title of Scoreboard (Animation Support!)
  title:
    - ""
    - "" # Delete this line if you don't want animations
  # The content of your scoreboard. You can also use Placeholders
  content:
    - ""
    - ""
    - ""

commands:
  help:
    enabled: true
    display-list-of-commands: true
    list-of-commands: ["/msg", "/lobby"]
    display-custom-text: false
    custom-text: ""

inventories:
  server-selector:
    filler:
      material: LIGHT_GRAY_STAINED_GLASS_PANE
      amount: 1
      displayname: " "
      lore:
        - ""
      actions: []

tablist:
  speed: 1 # Update Rate. 0 To disable
  world: "world"
  header:
    - "&cExample1"
    - "Example2"
  footer:
    - "Example1"
    - "§aExample2"

# Don't touch this!!! This will break the plugin if you change it!
config-version: "v0.1"