name: StarLobby
version: '1.0'
main: de.creeperbuildings.starlobby.Main
api-version: 1.13
authors: [CreeperBuildings, PhastixTV, ech0_Schokolade, Julian Weinelt]
description: A complete feature-packed lobby plugin.
depend:
  - PlaceholderAPI

permissions:
  starlobby:
    children:
      admin:
        children:
          - notify-update
          - main-command
      command:
        children:
          help:
            default: true
            description: Custom Help Command
          gm:
            children:
              - gma
              - gms
              - gmc
              - gmsp
          vanish:
            description: Vanish Command


commands:
  gma:
    aliases:
      - gmc
      - gms
      - gmsp
  help:
    aliases:
      - h